import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeModeScript } from 'flowbite-react';
import NavbarPage from '../components/NavbarPage/NavbarPage';
import FooterPage from '../components/FooterPage/FooterPage';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Israel Ramos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${inter.className} antialiased`}>
        <NavbarPage />
        <main className="relative min-h-screen">{children}</main>
        <FooterPage />
      </body>
    </html>
  );
}
